default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: metal-god
  password:
  host: localhost

development:
  <<: *default
  database: metal-god_development

test:
  <<: *default
  database: metal-god_test

production:
  <<: *default
  password: <%= ENV['METAL_GOD_DATABASE_PASSWORD'] %>
